spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace